name: CI
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v24
    - uses: ryanccn/attic-action@v0
      with:
        endpoint: https://cache.ners.ch
        cache: haskell
        token: ${{ secrets.ATTIC_TOKEN }}
    - name: Nix build
      run: nix build --accept-flake-config --print-build-logs
